--========================================================================================================================
-- LocalizedText
--========================================================================================================================
INSERT OR REPLACE INTO BaseGameText
		(Tag,					Text)
VALUES
--========================================================================================================================
-- ICELAND
--========================================================================================================================
		("LOC_CIVILIZATION_SUK_ICELAND_NAME",  
		"Iceland"	),
		("LOC_CIVILIZATION_SUK_ICELAND_DESCRIPTION",  
		"Icelandic Commonwealth"	),
		("LOC_CIVILIZATION_SUK_ICELAND_ADJECTIVE",  
		"Icelandic"	),
		-- RWF
		("LOC_CIVILIZATION_SUK_ICELAND_DESCRIPTION_JFD_CIVILIZATION",
		"Icelandic Civilization"),
--------------------------------------------------------------------
-- UA
--------------------------------------------------------------------
		("LOC_TRAIT_CIVILIZATION_SUK_SAGAS_OF_THE_ICELANDERS_NAME",  
		"Sagas of the Icelanders"	),
		("LOC_TRAIT_CIVILIZATION_SUK_SAGAS_OF_THE_ICELANDERS_DESCRIPTION",  
		"Historic Moments also provide [ICON_GreatWriter] Great Writer Points. Campuses, Theater Squares, and Commercial Hubs gain a Major adjacency bonus from Natural Wonders."),													 
		("LOC_TRAIT_CIVILIZATION_SUK_SAGAS_OF_THE_ICELANDERS_SCIENCE",  
		"+{1_num} [ICON_Science] Science from the adjacent natural {1_Num : plural 1?wonder; other?wonders;}."),
		("LOC_TRAIT_CIVILIZATION_SUK_SAGAS_OF_THE_ICELANDERS_CULTURE",  
		"+{1_num} [ICON_Culture] Culture from the adjacent natural {1_Num : plural 1?wonder; other?wonders;}."),
		("LOC_TRAIT_CIVILIZATION_SUK_SAGAS_OF_THE_ICELANDERS_GOLD",  
		"+{1_num} [ICON_Gold] Gold from the adjacent natural {1_Num : plural 1?wonder; other?wonders;}."),
		("LOC_TRAIT_CIVILIZATION_SUK_SAGAS_OF_THE_ICELANDERS_NOTIFICATION",  
		"{1} has written a saga to commemorate a Historic Moment, granting you +{2} [ICON_GreatWriter] Great Writer Points."),					
--------------------------------------------------------------------
-- Cities
--------------------------------------------------------------------	
		("LOC_CITY_NAME_SUK_ICELAND_REYKJAVIK",
		"Reykjavík"),
		("LOC_CITY_NAME_SUK_ICELAND_THINGVELLIR",
		"Þingvellir"),
		("LOC_CITY_NAME_SUK_ICELAND_HUSAVIK",
		"Húsavík"),
		("LOC_CITY_NAME_SUK_ICELAND_SKALHOLT",
		"Skálholt"),
		("LOC_CITY_NAME_SUK_ICELAND_HOLAR",
		"Hólar"),
		("LOC_CITY_NAME_SUK_ICELAND_AKUREYRI",
		"Akureyri"),
		("LOC_CITY_NAME_SUK_ICELAND_SEYTHISFJORTHUR",
		"Seyðisfjörður"),
		("LOC_CITY_NAME_SUK_ICELAND_GARTHABAER",
		"Garðabær"),
		("LOC_CITY_NAME_SUK_ICELAND_ISAFJORTHUR",
		"Ísafjörður"),
		("LOC_CITY_NAME_SUK_ICELAND_SAUTHARKROKUR",
		"Sauðárkrókur"),
		("LOC_CITY_NAME_SUK_ICELAND_BORGARNES",
		"Borgarnes"),
		("LOC_CITY_NAME_SUK_ICELAND_GARTHUR",
		"Garður"),
		("LOC_CITY_NAME_SUK_ICELAND_AKRANES",
		"Akranes"),
		("LOC_CITY_NAME_SUK_ICELAND_GRINDAVIK",
		"Grindavík"),
		("LOC_CITY_NAME_SUK_ICELAND_SELFOSS",
		"Selfoss"),
		("LOC_CITY_NAME_SUK_ICELAND_HAFNARFJORTHUR",
		"Hafnarfjörður"),
		("LOC_CITY_NAME_SUK_ICELAND_VESTMANNAEYJAR",
		"Vestmannaeyjar"),
		("LOC_CITY_NAME_SUK_ICELAND_KOPAVOGUR",
		"Kópavogur"),
		("LOC_CITY_NAME_SUK_ICELAND_KEFLAVIK",
		"Keflavík"),
		("LOC_CITY_NAME_SUK_ICELAND_EGILSSTATHIR",
		"Egilsstaðir"),
		("LOC_CITY_NAME_SUK_ICELAND_NESKAUPSTATHUR",
		"Neskaupstaður"),
		("LOC_CITY_NAME_SUK_ICELAND_STYKKISHOLMUR",
		"Stykkishólmur"),
		("LOC_CITY_NAME_SUK_ICELAND_MOSFELLSBAER",
		"Mosfellsbær"),
		("LOC_CITY_NAME_SUK_ICELAND_HVERAGERTHI",
		"Hveragerði"),
		("LOC_CITY_NAME_SUK_ICELAND_THORLAKSHOFN",
		"Þorlákshöfn"),
		("LOC_CITY_NAME_SUK_ICELAND_ALFTANES",
		"Álftanes"),
		("LOC_CITY_NAME_SUK_ICELAND_HOFN",
		"Höfn"),
		("LOC_CITY_NAME_SUK_ICELAND_SANDGERTHI",
		"Sandgerði"),
--------------------------------------------------------------------
-- Citizens
--------------------------------------------------------------------
		("LOC_CITIZEN_SUK_ICELAND_MALE_1",
		"Snorri"),
		("LOC_CITIZEN_SUK_ICELAND_MALE_2",
		"Yngvi"),
		("LOC_CITIZEN_SUK_ICELAND_MALE_3",
		"Haraldr"),
		("LOC_CITIZEN_SUK_ICELAND_MALE_4",
		"Sigfús"),
		("LOC_CITIZEN_SUK_ICELAND_MALE_5",
		"Úlfr"),
		("LOC_CITIZEN_SUK_ICELAND_MALE_6",
		"Týr"),
		("LOC_CITIZEN_SUK_ICELAND_MALE_7",
		"Baldr"),
		("LOC_CITIZEN_SUK_ICELAND_MALE_8",
		"Guðleifr"),
		("LOC_CITIZEN_SUK_ICELAND_MALE_9",
		"Þórr"),
		("LOC_CITIZEN_SUK_ICELAND_MALE_10",
		"Æsir"),

		("LOC_CITIZEN_SUK_ICELAND_FEMALE_1",
		"Sigga"),
		("LOC_CITIZEN_SUK_ICELAND_FEMALE_2",
		"Oddrún"),
		("LOC_CITIZEN_SUK_ICELAND_FEMALE_3",
		"Alfhildr"),
		("LOC_CITIZEN_SUK_ICELAND_FEMALE_4",
		"Unna"),
		("LOC_CITIZEN_SUK_ICELAND_FEMALE_5",
		"Ragnheiðr"),
		("LOC_CITIZEN_SUK_ICELAND_FEMALE_6",
		"Heiðrún"),
		("LOC_CITIZEN_SUK_ICELAND_FEMALE_7",
		"Eydís"),
		("LOC_CITIZEN_SUK_ICELAND_FEMALE_8",
		"Iórunnr"),
		("LOC_CITIZEN_SUK_ICELAND_FEMALE_9",
		"Alfríður"),
		("LOC_CITIZEN_SUK_ICELAND_FEMALE_10",
		"Laufey"),

		("LOC_CITIZEN_SUK_ICELAND_MODERN_MALE_1",
		"Ingólfur"),
		("LOC_CITIZEN_SUK_ICELAND_MODERN_MALE_2",
		"Kristján"),
		("LOC_CITIZEN_SUK_ICELAND_MODERN_MALE_3",
		"Emil"),
		("LOC_CITIZEN_SUK_ICELAND_MODERN_MALE_4",
		"Olav"),
		("LOC_CITIZEN_SUK_ICELAND_MODERN_MALE_5",
		"Guðmundur"),
		("LOC_CITIZEN_SUK_ICELAND_MODERN_MALE_6",
		"Arnar"),
		("LOC_CITIZEN_SUK_ICELAND_MODERN_MALE_7",
		"Jón"),
		("LOC_CITIZEN_SUK_ICELAND_MODERN_MALE_8",
		"Jóhann"),
		("LOC_CITIZEN_SUK_ICELAND_MODERN_MALE_9",
		"Tómas"),
		("LOC_CITIZEN_SUK_ICELAND_MODERN_MALE_10",
		"Björn"),

		("LOC_CITIZEN_SUK_ICELAND_MODERN_FEMALE_1",
		"Katrín"),
		("LOC_CITIZEN_SUK_ICELAND_MODERN_FEMALE_2",
		"Freyja"),
		("LOC_CITIZEN_SUK_ICELAND_MODERN_FEMALE_3",
		"Helga"),
		("LOC_CITIZEN_SUK_ICELAND_MODERN_FEMALE_4",
		"Hildur"),
		("LOC_CITIZEN_SUK_ICELAND_MODERN_FEMALE_5",
		"Margrét"),
		("LOC_CITIZEN_SUK_ICELAND_MODERN_FEMALE_6",
		"Högna"),
		("LOC_CITIZEN_SUK_ICELAND_MODERN_FEMALE_7",
		"Yrsa"),
		("LOC_CITIZEN_SUK_ICELAND_MODERN_FEMALE_8",
		"Björk"),
		("LOC_CITIZEN_SUK_ICELAND_MODERN_FEMALE_9",
		"Ágústa"),
		("LOC_CITIZEN_SUK_ICELAND_MODERN_FEMALE_10",
		"Halldóra"),
		
		--====================================================
		--- Genitive Forms (For UA flavour)
		--====================================================

		("LOC_CITIZEN_SUK_ICELAND_MALE_1_GENITIVE",
		"Snorra"),
		("LOC_CITIZEN_SUK_ICELAND_MALE_2_GENITIVE",
		"Yngva"),
		("LOC_CITIZEN_SUK_ICELAND_MALE_3_GENITIVE",
		"Haralds"),
		("LOC_CITIZEN_SUK_ICELAND_MALE_4_GENITIVE",
		"Sigfús"),
		("LOC_CITIZEN_SUK_ICELAND_MALE_5_GENITIVE",
		"Úlfa"),
		("LOC_CITIZEN_SUK_ICELAND_MALE_6_GENITIVE",
		"Týs"),
		("LOC_CITIZEN_SUK_ICELAND_MALE_7_GENITIVE",
		"Baldurs"),
		("LOC_CITIZEN_SUK_ICELAND_MALE_8_GENITIVE",
		"Guðleifrs"),
		("LOC_CITIZEN_SUK_ICELAND_MALE_9_GENITIVE",
		"Þórra"),
		("LOC_CITIZEN_SUK_ICELAND_MALE_10_GENITIVE",
		"Æsis"),

		("LOC_CITIZEN_SUK_ICELAND_FEMALE_1_GENITIVE",
		"Sígrúnar"),
		("LOC_CITIZEN_SUK_ICELAND_FEMALE_2_GENITIVE",
		"Oddrúnar"),
		("LOC_CITIZEN_SUK_ICELAND_FEMALE_3_GENITIVE",
		"Alfhildar"),
		("LOC_CITIZEN_SUK_ICELAND_FEMALE_4_GENITIVE",
		"Unnu"),
		("LOC_CITIZEN_SUK_ICELAND_FEMALE_5_GENITIVE",
		"Ragnheiðar"),
		("LOC_CITIZEN_SUK_ICELAND_FEMALE_6_GENITIVE",
		"Heiðrúnar"),
		("LOC_CITIZEN_SUK_ICELAND_FEMALE_7_GENITIVE",
		"Eydísar"),
		("LOC_CITIZEN_SUK_ICELAND_FEMALE_8_GENITIVE",
		"Iórunnar"),
		("LOC_CITIZEN_SUK_ICELAND_FEMALE_9_GENITIVE",
		"Alfríðar"),
		("LOC_CITIZEN_SUK_ICELAND_FEMALE_10_GENITIVE",
		"Laufeyjar"),

		("LOC_CITIZEN_SUK_ICELAND_MODERN_MALE_1_GENITIVE",
		"Ingólfs"),
		("LOC_CITIZEN_SUK_ICELAND_MODERN_MALE_2_GENITIVE",
		"Kristjáns"),
		("LOC_CITIZEN_SUK_ICELAND_MODERN_MALE_3_GENITIVE",
		"Emils"),
		("LOC_CITIZEN_SUK_ICELAND_MODERN_MALE_4_GENITIVE",
		"Olavsson"),
		("LOC_CITIZEN_SUK_ICELAND_MODERN_MALE_5_GENITIVE",
		"Guðmunds"),
		("LOC_CITIZEN_SUK_ICELAND_MODERN_MALE_6_GENITIVE",
		"Arnars"),
		("LOC_CITIZEN_SUK_ICELAND_MODERN_MALE_7_GENITIVE",
		"Jóns"),
		("LOC_CITIZEN_SUK_ICELAND_MODERN_MALE_8_GENITIVE",
		"Jóhanns"),
		("LOC_CITIZEN_SUK_ICELAND_MODERN_MALE_9_GENITIVE",
		"Tómas"),
		("LOC_CITIZEN_SUK_ICELAND_MODERN_MALE_10_GENITIVE",
		"Björns"),

		("LOC_CITIZEN_SUK_ICELAND_MODERN_FEMALE_1_GENITIVE",
		"Katrínar"),
		("LOC_CITIZEN_SUK_ICELAND_MODERN_FEMALE_2_GENITIVE",
		"Freyju"),
		("LOC_CITIZEN_SUK_ICELAND_MODERN_FEMALE_3_GENITIVE",
		"Helgu"),
		("LOC_CITIZEN_SUK_ICELAND_MODERN_FEMALE_4_GENITIVE",
		"Hildar"),
		("LOC_CITIZEN_SUK_ICELAND_MODERN_FEMALE_5_GENITIVE",
		"Margrétar"),
		("LOC_CITIZEN_SUK_ICELAND_MODERN_FEMALE_6_GENITIVE",
		"Högnu"),
		("LOC_CITIZEN_SUK_ICELAND_MODERN_FEMALE_7_GENITIVE",
		"Yrsu"),
		("LOC_CITIZEN_SUK_ICELAND_MODERN_FEMALE_8_GENITIVE",
		"Björkar"),
		("LOC_CITIZEN_SUK_ICELAND_MODERN_FEMALE_9_GENITIVE",
		"Ágústu"),
		("LOC_CITIZEN_SUK_ICELAND_MODERN_FEMALE_10_GENITIVE",
		"Halldóru"),			
--------------------------------------------------------------------
-- Info
--------------------------------------------------------------------
		("LOC_CIVINFO_SUK_ICELAND_LOCATION",
		"Europe"),
		("LOC_CIVINFO_SUK_ICELAND_SIZE",
		"Est. 39.7 thousand square miles (102.7 thousand square km)"),
		("LOC_CIVINFO_SUK_ICELAND_POPULATION",
		"338,349 (2017 est.)"),
		("LOC_CIVINFO_SUK_ICELAND_CAPITAL",
		"Reykjavík"),
--------------------------------------------------------------------
-- Pedia
--------------------------------------------------------------------
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_ICELAND_CHAPTER_HISTORY_PARA_1",
		"The history of Iceland is a long and adventurous saga filled with many transitions and discoveries. When the first Viking settlers arrived in Iceland in the late 9th century A.D., they found an uninhabited island. Today Iceland is a thoroughly modern country – but evidence of past times and their rich cultural heritage is still visible everywhere you look."),
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_ICELAND_CHAPTER_HISTORY_PARA_2",
		"What we know of Iceland’s earliest settlers can be largely traced back to the Landnámabók, or the “Book of Settlements”, a five-part medieval manuscript that tells the story of the Norsemen discovering and settling the country in the 9th and 10th century. Ingólfur Arnarson is credited as Iceland’s first permanent settler, though he also arrived at the island with his brother-in-law, Hjörleifr Hróðmarsson, later killed by his slaves after settling at Mount Hjörleifshöfði, just east of modern-day Vík. Norwegian chieftains followed Ingólfur en masse through the next few decades to escape the heavy-handed King Harald of Norway, and in about 60 years, Iceland was fully settled. By 930 AD, it is thought that all arable land in the country had been settled. Before the long period of growth, Iceland would soon experience, the settlement had grown so large that a new legislative body was in order; the ruling chiefs, therefore, established the Alþingi, which is believed by many to be the world’s oldest nation-wide parliament. The convening of the first Althing in 930 AD marks the beginning of the independent republic. This period of governance is known as the Icelandic Commonwealth (Þjóðveldið) or Free State; “The Golden Age of Iceland”."),
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_ICELAND_CHAPTER_HISTORY_PARA_3",
		"The period 930–1030 is known as The Saga Age, since many of the events recorded later (in the 12th and 13th century) in the Icelandic sagas actually took place during this time. Moreover, many of the key events related in the sagas happened at Thingvellir. It was also at Thingvellir in the year 999 or 1000 that Christianity was adopted in Iceland. 1120s-1230s, the Great Age of Writing, was an epoch of remarkable literary achievements. Most of the Icelandic sagas were written during this time, as well as the great historical works: Íslendingabók and Heimskringla. Íslendingabók, the first national history, was written around 1130 by Ari Þorgilsson (Thorgilsson), called fróði - Ari the Wise (1067-1148). Heimskringla (The History of Norwegian Kings) was written by Snorri Sturluson (1179-1241)."),
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_ICELAND_CHAPTER_HISTORY_PARA_4",
		"The year 1220 marks the beginnings of “The Age of the Sturlungs” - Sturlungaöld. This was a period of internal conflict in Iceland, and the last period in Iceland’s nearly 400 years as an independent free state. The Sturlungs were members of the most powerful family clan; amongst them were the authors of the classic Icelandic sagas. The most famous and greatest of them all was Snorri Sturluson. Through marriages and political alliances, the Sturlungs dominated great part of the country, but other chieftains and influential families opposed them. The prolonged feuds and power struggles between the chieftaincies brought about economic and social ruin. At the time, the Norwegian king Hákon Hákonarson (King Haakon IV) was attempting to extend his influence in Iceland, as part of his campaign to unite all Norwegian Viking Age settlements. Several of the greatest Icelandic chieftains had become the King’s liegemen, while Snorri Sturluson had fallen out of favour, due to his support for Earl Skúli, King Haakon’s rival. In 1241, at King Haakon’s instigation, Snorri Sturluson was killed in Reykholt. Ultimately, 1262-1264, Icelandic chieftains were persuaded to swear allegiance to King Haakon IV of Norway, partly in the hope that he would bring peace to the country. 1262 marks the end of the Icelandic Commonwealth period."),
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_ICELAND_CHAPTER_HISTORY_PARA_5",
		"Under the Norwegian Crown, Icelanders became dependent on Norwegian ships for supplies, which often failed to come. A period of great hardship and desolation followed. Ice often blocked the fjords and the sea approaches. Violent volcanic eruptions, recurring epidemics and famine ravaged the entire country. In 1349 the Black Death afflicted Norway, cutting off all trade and supplies. In 1380 the Norwegian monarchy entered into a union with Denmark; however, the change did not effect Iceland’s status. When in 1397 the Kalmar Union was formed between Sweden, Norway and Denmark, Iceland came under the dominant Danish crown. The conditions in the country worsened further. Icelandic chieftains were replaced by Danish royal officials. Althing became a court of law; judges were chosen by royal officers. At the beginning of the 15th century, 1402-1404, the Black Death afflicted Iceland, killing more than a third of the population. In the period 1540-1550 Lutheranism was imposed on Iceland by the order of the Danish king, and first Lutheran bishop installed in Skálholt. The opposition to the Reformation in Iceland ended in 1550 when the last Catholic bishop, Jón Arason, was beheaded. In 1602 Denmark established a trade monopoly, forbidding Iceland to trade with any country other than Denmark, precipitating a period of extreme destitution. The monopoly remained in effect until 1787. The Danish Crown tightened its grip on Iceland on the constitutional level as well. In 1662, the Danish King assumed hereditary power, absolute monarchy was imposed in Iceland and the power of Althing significantly declined. The 18th century in Iceland was a tragic period of population decline, increasing poverty and natural calamities. In 1703 when the first census of Iceland was conducted, the population numbered 50,366, and about 20% were destitute. After the smallpox epidemic in 1707, around 18,000 people perished. The series of natural disasters and famines that followed in their wake caused population decline to well below 40,000 twice more during the century. Katla volcano erupted in 1755 and in 1783 the catastrophic Laki eruption (Lakagígar) occurred, causing floods, ash and toxic fumes and the ensuing starvation killed 10,000 people. "),
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_ICELAND_CHAPTER_HISTORY_PARA_6",
		"In 1800 the Althing was dissolved by royal decree and later replaced by the Supreme Court. However, by the middle of the 19th century a new national consciousness was revived in Iceland, and Jón Sigurðsson had become the great leader of the Icelandic independence movement. In 1843 the Althing was re-established as a consultative body, but only a few powerful feudal barons and landowners were elected. When in 1848 King Frederick VII of Denmark renounced his absolute power, it also led to the question of Iceland’s status in the new form of government. Jón Sigurðsson’s stance was that the king could only give his absolute power rule over Iceland back to the Icelanders themselves, since they were the ones who had relinquished it to the Danish Crown in 1662. In addition, Iceland had originally entered the union with the Norwegian monarchy as a free state with certain rights vouchsafed under the agreement from 1262-1264. In 1854 the Danish trade monopoly lifted, finally granting Iceland complete freedom of trade. Freedom of press was established in 1855. In 1874 the millennium celebrations of the Settlement were held and King Christian IX of Denmark visited Iceland. He presented Iceland with a new constitution, granting the Althing legislative power in internal affairs. In 1904 the constitution was amended, and Iceland got home rule under Denmark. The first Icelandic minister was established in Reykjavik. "),
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_ICELAND_CHAPTER_HISTORY_PARA_7",
		"Whilst the years of home rule (1904-1918) were characterized by progress in economic and social spheres, Iceland’s struggle for greater autonomy continued. On 1 December 1918, Iceland became a sovereign state, the Kingdom of Iceland, in a personal union with the Danish king.  1944, Iceland rescinded its union with Denmark, and the Republic of Iceland was founded at Thingvellir. The proclamation of the Republic of Iceland marked the end of seven centuries of foreign rule.  A new epoch in the history of Iceland had begun."),
--========================================================================================================================
-- Unique Unit
--========================================================================================================================
		("LOC_UNIT_SUK_LAWSPEAKER_NAME",  
		"Lawspeaker"	),
		("LOC_UNIT_SUK_LAWSPEAKER_DESCRIPTION",  
		"Icelandic unique civilian unit. The Lawspeaker provides +3 Loyalty per turn when garrisoned in a City Center, or gives +50% adjacency bonuses when garrisoned in a District. Lawspeakers can only be trained in your [ICON_Capital] Capital."),
		("LOC_PEDIA_UNITS_PAGE_UNIT_SUK_LAWSPEAKER_CHAPTER_HISTORY_PARA_1",  
		"The Lawspeaker (lögsögumadur) was the highest official of Althing. The Lawspeaker's role was to recite the laws of Iceland at Althing, in the days before Iceland had a written language. He recited the laws of parliamentary procedure, chaired court sessions, and settled disputes. The Lawspeaker is believed to have addressed the assembly from the Law Rock, which was where verdicts were announced, important speeches made, and where the assembly was formally opened and dissolved. Much remains unclear about the assembly and the role of the Lawspeaker, as the Old Commonwealth was a time of change in Icelandic society, and disputes over power and religion made their mark on society and on the work of Althing."),
--========================================================================================================================
-- Unique Infrastructure
--========================================================================================================================
		("LOC_DISTRICT_SUK_TORFBAEIR_NAME",  
		"Torfbæir"	),
		("LOC_DISTRICT_SUK_TORFBAEIR_DESCRIPTION",  
		"A district unique to Iceland for city growth. Replaces the Aqueduct district.[NEWLINE][NEWLINE]Instead of the Aqueduct's usual restrictions and bonuses, Torfbæir provide +3 [ICON_Housing] Housing, +1 [ICON_Food] Food and +1 [ICON_Production] Production. This bonus increases to +4 [ICON_Housing], +2 [ICON_Food] and +2 [ICON_Production] when built on tiles with Charming Appeal, or to +5 [ICON_Housing], +3 [ICON_Food] and +3 [ICON_Production] when built on tiles with Breathtaking Appeal. Torfbæir cannot be built on Desert tiles."),
		("LOC_PEDIA_DISTRICTS_PAGE_DISTRICT_SUK_TORFBAEIR_CHAPTER_HISTORY_PARA_1",  
		"When looking at pictures from Iceland, small and cute looking turf houses (Torfbæir) are bound to come up. Due to lack of trees in Iceland, building out of turf was a popular building material and thick turf walls were useful to ward off the cold. This technique of building with turf first appeared with the arrival of Norse and British settlers during the 9th through 11th centuries at the height of the Viking Age in Europe. Historic records suggest that up to 50 percent of Icelandic dwellings were partially comprised of turf until the late 19th century, though this number began declining in the 20th century. By 1960 there were 234 inhabited turf homes in Iceland, most of which were deserted in the next decade."),		
		("LOC_DISTRICT_SUK_TORFBAEIR_APPEAL_FOOD",  
		"+{1_num} [ICON_Food] Food from the tile's Appeal."	),
		("LOC_DISTRICT_SUK_TORFBAEIR_APPEAL_HOUSING_BASE",  
		"Average or less"	),
		("LOC_DISTRICT_SUK_TORFBAEIR_APPEAL_HOUSING_CHARMING",  
		"Charming"	),
		("LOC_DISTRICT_SUK_TORFBAEIR_APPEAL_HOUSING_BREATHTAKING",  
		"Breathtaking"	),			
--========================================================================================================================
-- Leader
--========================================================================================================================
		("LOC_LEADER_SUK_INGOLFUR_NAME",  
		"Ingólfur Arnarson"	),
--------------------------------------------------------------------
-- ULA
--------------------------------------------------------------------
		("LOC_TRAIT_LEADER_SUK_BOOK_OF_SETTLEMENTS_NAME",  
		"Book of Settlements"	),
		("LOC_TRAIT_LEADER_SUK_BOOK_OF_SETTLEMENTS_DESCRIPTION",  
		"Your cities on foreign continents receive +2 Loyalty and +1 [ICON_GreatWriter] Great Writer Point per turn. Cities within 2 tiles of a Natural Wonder also receive +2 Loyalty and +1 [ICON_GreatWriter] Great Writer Point per turn. +1 to each of these bonuses in a [ICON_GLORY_DARK_AGE] Dark Age."),
--------------------------------------------------------------------
-- Agenda
--------------------------------------------------------------------
		("LOC_AGENDA_SUK_BAY_OF_SMOKE_NAME",  
		"Bay of Smoke"	),
		("LOC_AGENDA_SUK_BAY_OF_SMOKE_DESCRIPTION",  
		"Likes civilizations that explore the map and have settled near Natural Wonders. Dislikes civilizations that have no interest in exploring."	),

		("LOC_DIPLO_KUDO_EXIT_LEADER_SUK_INGOLFUR_ANY",  
		"(You own natural wonders and are exploring the map.)"	),
		("LOC_DIPLO_MODIFIER_SUK_BAY_OF_SMOKE_KUDO",  
		"Ingólfur admires your natural wonders and adventurous spirit"	),

		("LOC_DIPLO_WARNING_EXIT_LEADER_SUK_INGOLFUR_ANY",  
		"(You aren't exploring the map.)"	),
		("LOC_DIPLO_MODIFIER_SUK_BAY_OF_SMOKE_WARNING",  
		"Ingólfur is disappointed by your lack on interest in exploration"	),
--------------------------------------------------------------------
-- RWF Support
--------------------------------------------------------------------
		("LOC_GOVERNMENT_JFD_CHIEFDOM_LEADER_TITLE_SUK_ICELAND",
		"Goði"),
		("LOC_GOVERNMENT_JFD_HORDE_LEADER_TITLE_SUK_ICELAND",
		"Warchief"),
		("LOC_GOVERNMENT_JFD_POLIS_LEADER_TITLE_SUK_ICELAND",
		"Bæjarstjóri"),
		("LOC_GOVERNMENT_JFD_CLASSICAL_DEMOCRACY_LEADER_TITLE_SUK_ICELAND",
		"Lawspeaker"),
		("LOC_GOVERNMENT_JFD_AUTOCRACY_LEADER_TITLE_NORWAY",
		"Jarl"),
		("LOC_GOVERNMENT_JFD_OLIGARCHY_LEADER_TITLE_SUK_ICELAND",
		"Thegn"),
		("LOC_GOVERNMENT_JFD_MERCHANT_REPUBLIC_LEADER_TITLE_SUK_ICELAND",
		"Councillor"),	
		("LOC_GOVERNMENT_JFD_FEUDAL_MONARCHY_LEADER_TITLE_SUK_ICELAND",
		"King"),
		("LOC_GOVERNMENT_JFD_MONARCHY_LEADER_TITLE_SUK_ICELAND",
		"High King"),
		("LOC_GOVERNMENT_JFD_NOBLE_REPUBLIC_LEADER_TITLE_SUK_ICELAND",
		"High Councillor"),
		("LOC_GOVERNMENT_JFD_LIBERAL_DEMOCRACY_LEADER_TITLE_SUK_ICELAND",
		"Forseti"),
		("LOC_GOVERNMENT_JFD_MILITARY_GUARDIANSHIP_LEADER_TITLE_SUK_ICELAND",
		"Inspector General"),
		("LOC_GOVERNMENT_JFD_PEOPLES_REPUBLIC_LEADER_TITLE_SUK_ICELAND",
		"General Secretary"),	
		("LOC_GOVERNMENT_JFD_EMPIRE_LEADER_TITLE_SUK_ICELAND",
		"Emperor"),									
--------------------------------------------------------------------
-- Diplo
--------------------------------------------------------------------
		("LOC_LOADING_INFO_LEADER_SUK_INGOLFUR",  
		"Venture forth Ingólfur Arnarson, for the world is wide and full of wonder! Distant lands hold great opportunities as well as great hardships, but rest assured that your people's resilience and ingenuity will carry Iceland ever onwards. The Age of Settlement is upon you, and the stories you forge today will live on forever in the Sagas."  	),
		("LOC_DIPLO_REJECT_DECLARE_FRIEND_FROM_AI_LEADER_SUK_INGOLFUR_ANY",                                      
        "Maybe next time then."),
        ("LOC_DIPLO_ACCEPT_DECLARE_FRIEND_FROM_AI_LEADER_SUK_INGOLFUR_ANY",                                      
        "Good, good."),
        ("LOC_DIPLO_DECLARE_FRIEND_FROM_AI_LEADER_SUK_INGOLFUR_ANY",                                     
        "The world is harsh. Let us work together as friends"),
        ("LOC_DIPLO_REJECT_DECLARE_FRIEND_FROM_HUMAN_LEADER_SUK_INGOLFUR_ANY",                                     
        "While I would love to say yes, the Althing thinks it best to wait a little longer."),
        ("LOC_DIPLO_ACCEPT_DECLARE_FRIEND_FROM_HUMAN_LEADER_SUK_INGOLFUR_ANY",                                     
        "I heartily accept! Let me bring out some ale to celebrate!"),
        ("LOC_DIPLO_DECLARE_WAR_FROM_AI_LEADER_SUK_INGOLFUR_ANY",                                      
        "We fight for glory! The Skalds shall sing and write poems of our coming battles!"), 
        ("LOC_DIPLO_DECLARE_WAR_FROM_HUMAN_LEADER_SUK_INGOLFUR_ANY",                                     
        "Our men are tough, or they would not have settled here. Do you truly think your warriors can match their mettle?"), 
        ("LOC_DIPLO_DEFEAT_FROM_HUMAN_LEADER_SUK_INGOLFUR_ANY",                                      
        "And thus my journey comes to an end. At least my story will live on in the sagas."),
        ("LOC_DIPLO_DEFEAT_FROM_AI_LEADER_SUK_INGOLFUR_ANY",                                     
        "And thus my journey comes to an end. At least my story will live on in the sagas."),
        ("LOC_DIPLO_DELEGATION_FROM_AI_LEADER_SUK_INGOLFUR_ANY",                                     
        "I've sent you an assortment of Þorramatur. There's Svið, Harðfiskur, and Hákarl! Enjoy!"),
        ("LOC_DIPLO_REJECT_DELEGATION_FROM_HUMAN_LEADER_SUK_INGOLFUR_ANY",                                     
        "I regret to say that the Althing has decided against it."),
        ("LOC_DIPLO_ACCEPT_DELEGATION_FROM_HUMAN_LEADER_SUK_INGOLFUR_ANY",                                     
        "I welcomed them personally into my home."),
        ("LOC_DIPLO_DENOUNCE_FROM_AI_LEADER_SUK_INGOLFUR_ANY",                                     
        "What does it say that even I cannot stand you? (Denounces You)"),
        ("LOC_DIPLO_DENOUNCE_FROM_HUMAN_LEADER_SUK_INGOLFUR_ANY",                                      
        "You would insult me? I promise you will regret these words."),
        ("LOC_DIPLO_FIRST_MEET_LEADER_SUK_INGOLFUR_ANY",                                     
        "I am Ingólfur Arnarson. On behalf of the Althing, I welcome you to Iceland, and to my humble homestead."),
        ("LOC_DIPLO_FIRST_MEET_VISIT_RECIPIENT_LEADER_SUK_INGOLFUR_ANY",                                     
        "We have a little settlement nearby. You should visit! We can't have people saying that we Icelanders aren't hospitable!"),
        ("LOC_DIPLO_FIRST_MEET_NEAR_INITIATOR_POSITIVE_LEADER_SUK_INGOLFUR_ANY",                                     
        "Yes! It will be excellent seeing new lands!"),
        ("LOC_DIPLO_FIRST_MEET_NO_MANS_INFO_EXCHANGE_LEADER_SUK_INGOLFUR_ANY",                                     
        "Our main settlement doesn't have too much right now. But the hot springs are excellent! That's why we call it Reykjarvík!"),
        ("LOC_DIPLO_GREETING_LEADER_SUK_INGOLFUR_ANY",                                     
        "Hail!"),
        ("LOC_DIPLO_WARNING_EXIT_LEADER_SUK_INGOLFUR_ANY",                                     
        "Have you no sense of adventure? You have no idea of the wonders the world holds."),
        ("LOC_DIPLO_KUDO_EXIT_LEADER_SUK_INGOLFUR_ANY",                                      
        "Living in the shadow of such majestic wonders gives one a great urge to explore, doesn't it?"),
        ("LOC_DIPLO_MAKE_ALLIANCE_FROM_AI_LEADER_SUK_INGOLFUR_ANY",                                      
        "Would you like to form an alliance?"),
        ("LOC_DIPLO_REJECT_MAKE_DEAL_FROM_AI_LEADER_SUK_INGOLFUR_ANY",                                     
        "A shame."),
        ("LOC_DIPLO_ACCEPT_MAKE_DEAL_FROM_AI_LEADER_SUK_INGOLFUR_ANY",                                     
        "Good!"),
        ("LOC_DIPLO_MAKE_PEACE_AI_ACCEPT_DEAL_LEADER_SUK_INGOLFUR_ANY",                                      
        "Well fought. We have both earned this peace."),
        ("LOC_DIPLO_MAKE_PEACE_AI_REFUSE_DEAL_LEADER_SUK_INGOLFUR_ANY",                                      
        "That offer is almost offensive."),
        ("LOC_DIPLO_MAKE_PEACE_FROM_AI_LEADER_SUK_INGOLFUR_ANY",                                     
        "We have both proven our bravery. It is time for the bloodshed to end."),
        ("LOC_DIPLO_ACCEPT_OPEN_BORDERS_FROM_HUMAN_LEADER_SUK_INGOLFUR_ANY",                                     
        "Why not? The wonders of this land deserve to be shared."),
        ("LOC_DIPLO_REJECT_OPEN_BORDERS_FROM_HUMAN_LEADER_SUK_INGOLFUR_ANY",                                     
        "I'm sorry, but I can't allow this."),
        ("LOC_DIPLO_OPEN_BORDERS_FROM_AI_LEADER_SUK_INGOLFUR_ANY",                                     
        "Will you permit us passage through your lands?"),
        ("LOC_DIPLO_WARNING_TOO_MANY_TROOPS_NEAR_ME_LEADER_SUK_INGOLFUR_ANY",                                      
        "You do realise the only ones intimidated by that army are the sheep, right?"),
--------------------------------------------------------------------
-- Quote and Pedia
--------------------------------------------------------------------
		("LOC_PEDIA_LEADERS_PAGE_SUK_INGOLFUR_QUOTE",  
		"Every man is the smith of his own fortune."  	), -- Hver er sinnar gæfu smiður.
		("LOC_PEDIA_LEADERS_PAGE_SUK_INGOLFUR_TITLE",
		"Ingólfur Arnarson"),
		("LOC_PEDIA_LEADERS_PAGE_SUK_INGOLFUR_SUBTITLE",
		"First Norse Settler of Iceland"),
		("LOC_PEDIA_LEADERS_PAGE_LEADER_SUK_INGOLFUR_CHAPTER_CAPSULE_BODY",
		"Embrace new lands and new challenges with Iceland. Led by Ingólfur, their first settler, you can safely settle ever more distant shores."),
		("LOC_PEDIA_LEADERS_PAGE_LEADER_SUK_INGOLFUR_CHAPTER_DETAILED_BODY",
		"Iceland is the civ for explorers and writers. Send out scouts early to gain Historic Moments (and [ICON_GreatWriter] Great Writer Points), and spot potential spot for further settlements. Natural wonders will be particularly valuable: many of your districts get a major bonus from being adjacent to them! Torfbæir will relieve reliance on fresh water as they can be built anywhere except on desert tiles, and provide a small amount of [ICON_Food] Food and [ICON_Production] to help get your cities up and running. The Lawspeaker, while expensive, provides a further boost, giving you extra Loyalty and Yields where you need it. Under Ingólfur, gaining a foothold on distant lands is easier, with Loyalty and [ICON_GreatWriter] Great Writer Point boosts."),
		("LOC_PEDIA_LEADERS_PAGE_LEADER_SUK_INGOLFUR_CHAPTER_HISTORY_PARA_1",
		"According to Landnámabók (a medieval manuscript detailing the Norse settlement of Iceland), Ingólfur Arnarson is widely ascribed to have been one of the first permanent settlers of Iceland, alongside his wife, Hallveig Fróðadóttir, and his foster brother Hjörleifur Hróðmarsson. A nobleman of Norwegian descent, Ingólfur (his name literally meaning ‘noble wolf’) was forced to leave early medieval Norway during the late part of the 9th century in the wake of a skirmish in which he and his foster brother took part against the sons of a powerful Norse jarl (earl). So it is that after he had murdered two of the Norse jarl’s sons he was forced to give up all of his land possessions to him. Having virtually speaking nothing to stand for in his native land, Ingólfur decided to set sail westward, in a quest for a better life."),
		("LOC_PEDIA_LEADERS_PAGE_LEADER_SUK_INGOLFUR_CHAPTER_HISTORY_PARA_2",
		"At some point throughout the early 870s, he embarked along with his wife, Hjörleifur’s family, some slaves in their service, and anything else valuable that they could pack up. Among these things were a pair of stone pillars he had thrown off board while in the proximity of Iceland. Because he wanted to live in a place directed by divine intervention, these pillars represented the will of the Norse gods. Thereupon, when the pillars reached the shores of Iceland Ingólfur knew he had to settle there. Shortly thereafter, he and his crew spent their first winter on Icelandic soil at the Ingólfshöfði headland which is situated in the southern coast of Iceland. Subsequently, he sent two of his slaves to scout the surroundings in the search for the drifted pillars. They have done so all the way on the south-western coast of Iceland until they saw them in a bay with some hot springs. Thus, in 874, Ingólfur Arnarson is credited for being the founder of Iceland’s capital city, which was originally named, Reykjarvík (or the ‘Smoky Bay’ as it literally translates to in English) by building his new farmstead there. He named the place this way because of the ‘smoke’ (actually steam) which came up from the hot springs in the vicinity of present day Reykjavík."),
		("LOC_PEDIA_LEADERS_PAGE_LEADER_SUK_INGOLFUR_CHAPTER_HISTORY_PARA_3",
		"It must be equally mentioned that Ingólfur was, even for a relatively brief period of time, the legal owner of the south-western part of the island, but since he could not inhabit all of it he had either donated or sold much of his land property to the upcoming waves of Scandinavian colonists who took part in the Norse settlement phase of Iceland. Nowadays, on a small hill called Arnarhóll in the middle of Reykjavík stands a statue erected in the honour of Ingólfur."),
		("LOC_PEDIA_LEADERS_PAGE_LEADER_SUK_INGOLFUR_CHAPTER_HISTORY_PARA_4",
		"Nonetheless, not much is known regarding Ingólfur’s fate after the foundation of Reykjavik. What is for certain though, is that his son Þorsteinn (Torstein) grew up to become a noteworthy chieftain in Viking Age Iceland and is also remembered for his efforts of establishing one of the country’s first assemblies at Kjalarnes, currently a district of the capital city.");
--------------------------------------------------------------------
--------------------------------------------------------------------